/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0040a1",
        "primary-container": "#0056d2",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#ccd8ff",
        "on-primary-fixed": "#001847",
        "on-primary-fixed-variant": "#0040a1",
        "secondary": "#006d37",
        "secondary-container": "#76f9a0",
        "secondary-fixed": "#79fca2",
        "secondary-fixed-dim": "#5adf88",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00723a",
        "on-secondary-fixed": "#00210c",
        "on-secondary-fixed-variant": "#005228",
        "tertiary": "#745b00",
        "tertiary-container": "#d0a600",
        "tertiary-fixed": "#ffe08b",
        "tertiary-fixed-dim": "#f0c110",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4f3d00",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#584400",
        "background": "#fcf9f8",
        "on-background": "#1b1b1c",
        "surface": "#fcf9f8",
        "on-surface": "#1b1b1c",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-variant": "#e5e2e1",
        "on-surface-variant": "#424654",
        "surface-tint": "#0056d2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#b2c5ff",
        "outline": "#737785",
        "outline-variant": "#c3c6d6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "grid-unit": "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "gutter": "24px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "max-width": "1600px"
      },
      maxWidth: {
        "max-width": "1600px",
        "desktop-xl": "1680px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      boxShadow: {
        "ambient": "0 1px 3px rgba(0, 0, 0, 0.05)",
        "elevation-1": "0 2px 8px -2px rgba(0, 0, 0, 0.08), 0 1px 4px -1px rgba(0, 0, 0, 0.04)",
        "elevation-2": "0 4px 16px -4px rgba(0, 0, 0, 0.1), 0 2px 6px -1px rgba(0, 0, 0, 0.06)",
        "elevation-3": "0 12px 32px -4px rgba(0, 0, 0, 0.12), 0 4px 12px -2px rgba(0, 0, 0, 0.08)",
      }
    },
  },
  plugins: [],
}
